/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.contract.annotation.Contact;
import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.annotation.Info;
import org.hyperledger.fabric.contract.annotation.License;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.shim.ChaincodeException;
import org.hyperledger.fabric.shim.ChaincodeStub;

import com.owlike.genson.Genson;

@Contract(
        name = "document",
        info = @Info(
                title = "Document Logic",
                description = "Document Contract",
                version = "0.0.1",
                license = @License(
                        name = "Vish License",
                        url = "vish.com"),
                contact = @Contact(
                        email = "vish@vish.com",
                        name = "VishaanKhanna",
                        url = "https:vish.document.com")))
                        
@Default
public final class DocumentTransfer implements ContractInterface {

    private final Genson genson = new Genson();

    private enum DocuementTransferErrors {
        DOCUMENT_NOT_FOUND,
        DOCUMENT_ALREADY_EXISTS
    }



        /**
     * Creates some initial assets on the ledger.
     *
     * @param ctx the transaction context
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public void InitLedger(final Context ctx) {
        ChaincodeStub stub = ctx.getStub();

        CreateDocument(ctx, "doc1", "To Kill", "John2", "279o9ohuisdg78928h", "PDF",false);
        CreateDocument(ctx, "doc2", "Some Legal Document", "Dave1", "8fjiruenguiu759uw", "Docx",false);


    }

    /**
     * Create Document
     * @param ctx
     * @param documentID
     * @param documentName
     * @param creatorID
     * @param documentHash
     * @param documentType
     * @param signable
     * @return
     */
    @Transaction(intent=Transaction.TYPE.SUBMIT)
    public Document CreateDocument(final Context ctx,final String documentID, final String documentName , final String creatorID, final String documentHash,
                                final String documentType , final boolean signable){

        ChaincodeStub stub = ctx.getStub();

        //check if a document of that name exists 
        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        Document newDoc = new Document(documentID,creatorID, documentName, documentHash, documentType, signable);

        // Use Genson to convert the Asset into string, sort it alphabetically and serialize it into a json string
        String sortedJson = genson.serialize(newDoc);
        stub.putStringState(documentName, sortedJson);

        return newDoc;

    }

    /**
     * Check that the document exists on ledger
     * @param ctx transaction context
     * @param documentID document id
     * @return true or false indicating assets existance 
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public boolean CheckDocumentExists(final Context ctx, final String documentID){
        ChaincodeStub stub = ctx.getStub();
        String documentJSON = stub.getStringState(documentID);
        
        return (documentJSON != null && !documentJSON.isEmpty());

    }

    /**
     * Check that the hash of the document equals the hash on ledger to verify the authenticity of the document
     * @param ctx transaction context
     * @param documentID doc id
     * @param documentHash hash to check 
     * @return
     */
    @Transaction(intent= Transaction.TYPE.EVALUATE)
    public boolean CheckDocumentValidity(final Context ctx, final String documentID, final String documentHash){
        ChaincodeStub stub = ctx.getStub();
        
        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document fetchedDoc = genson.deserialize(documentJSON,Document.class);
     

        // Access the documentHash field
        String fetchedHash = fetchedDoc.getDocumentHash();


        return documentHash.equals(fetchedHash);
    }

    /**
     * Read a document
     * @param ctx
     * @param documentName
     * @return
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public Document ReadDocument(final Context ctx, final String documentID){
        ChaincodeStub stub = ctx.getStub();
        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document fetchedDoc = genson.deserialize(documentJSON,Document.class);
        
        return fetchedDoc;

    }

    /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentHash(Context ctx, final String documentID, final String hash){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setHash(hash);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }


        /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentName(Context ctx, final String documentID, final String newdocumentName){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setName(newdocumentName);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }

        /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentSignable(Context ctx, final String documentID, final boolean signable){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setSignable(signable);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }

        /**
     * Deletes document on the ledger.
     *
     * @param ctx the transaction context
     * @param assetID the ID of the asset being deleted
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public void DeleteDocument(final Context ctx, final String documentID) {
        ChaincodeStub stub = ctx.getStub();

        if (!CheckDocumentExists(ctx, documentID)) {
            String errorMessage = String.format("Asset %s does not exist", documentID);
            System.out.println(errorMessage);
            throw new ChaincodeException(errorMessage, DocuementTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        stub.delState(documentID);
    }

    

    


}