/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;
import java.util.List;

import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.contract.annotation.Contact;
import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.annotation.Info;
import org.hyperledger.fabric.contract.annotation.License;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.shim.ChaincodeException;
import org.hyperledger.fabric.shim.ChaincodeStub;
import org.hyperledger.fabric.shim.ledger.KeyValue;
import org.hyperledger.fabric.shim.ledger.QueryResultsIterator;

import com.owlike.genson.Genson;

@Contract(
        name = "document",
        info = @Info(
                title = "Document Logic",
                description = "Document Contract",
                version = "0.0.1",
                license = @License(
                        name = "Vish License",
                        url = "vish.com"),
                contact = @Contact(
                        email = "vish@vish.com",
                        name = "VishaanKhanna",
                        url = "https:vish.document.com")))
                        
@Default
public final class DocumentTransfer implements ContractInterface {

    private final Genson genson = new Genson();

    private enum DocumentTransferErrors {
        DOCUMENT_NOT_FOUND,
        DOCUMENT_ALREADY_EXISTS
    }



        /**
     * Creates some initial assets on the ledger.
     *
     * @param ctx the transaction context
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public void InitLedger(final Context ctx) {
        ChaincodeStub stub = ctx.getStub();

        CreateDocument(ctx, "doc1", "To Kill", "John2", "279o9ohuisdg78928h", "PDF",false);
        CreateDocument(ctx, "doc2", "Some Legal Document", "Dave1", "8fjiruenguiu759uw", "Docx",false);


    }

    /**
     * Create Document
     * @param ctx
     * @param documentID
     * @param documentName
     * @param creatorID
     * @param documentHash
     * @param documentType
     * @param signable
     * @return
     */
    @Transaction(intent=Transaction.TYPE.SUBMIT)
    public Document CreateDocument(final Context ctx,final String documentID, final String documentName , final String creatorID, final String documentHash,
                                final String documentType , final boolean signable){

        ChaincodeStub stub = ctx.getStub();

        //check if a document of that id exists 
        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
            //if exists exit with error
            if (documentJSON != null && !documentJSON.isEmpty()) {
                throw new ChaincodeException("Document already exists for ID: " + documentID, DocumentTransferErrors.DOCUMENT_ALREADY_EXISTS.toString());
            }

        Document newDoc = new Document(documentID,creatorID, documentName, documentHash, documentType, signable);

        // Use Genson to convert the Asset into string, sort it alphabetically and serialize it into a json string
        String sortedJson = genson.serialize(newDoc);
        stub.putStringState(documentID, sortedJson);

        return newDoc;

    }

    /**
     * Check that the document exists on ledger
     * @param ctx transaction context
     * @param documentID document id
     * @return true or false indicating assets existance 
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public boolean CheckDocumentExists(final Context ctx, final String documentID){
        ChaincodeStub stub = ctx.getStub();
        String documentJSON = stub.getStringState(documentID);
        
        return (documentJSON != null && !documentJSON.isEmpty());

    }

    /**
     * Check that the hash of the document equals the hash on ledger to verify the authenticity of the document
     * @param ctx transaction context
     * @param documentID doc id
     * @param documentHash hash to check 
     * @return
     */
    @Transaction(intent= Transaction.TYPE.EVALUATE)
    public boolean CheckDocumentValidity(final Context ctx, final String documentID, final String documentHash){
        ChaincodeStub stub = ctx.getStub();
        
        String documentJSON = stub.getStringState(documentID);

            // Check if the is null
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document fetchedDoc = genson.deserialize(documentJSON,Document.class);
     

        // Access the documentHash field
        String fetchedHash = fetchedDoc.getDocumentHash();


        return documentHash.equals(fetchedHash);
    }

    /**
     * Read a document
     * @param ctx
     * @param documentName
     * @return
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public Document ReadDocument(final Context ctx, final String documentID){
        ChaincodeStub stub = ctx.getStub();
        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document fetchedDoc = genson.deserialize(documentJSON,Document.class);
        
        return fetchedDoc;

    }

    /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentHash(Context ctx, final String documentID, final String hash){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setHash(hash);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }


        /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentName(Context ctx, final String documentID, final String newdocumentName){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setName(newdocumentName);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }

        /**
     * Update the hash of an existing item 
     * @param ctx
     * @param documentName
     * @param hash
     * @return
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public Document UpdateDocumentSignable(Context ctx, final String documentID, final boolean signable){
        ChaincodeStub stub = ctx.getStub();

        String documentJSON = stub.getStringState(documentID);

            // Check if the document exists
        if (documentJSON == null || documentJSON.isEmpty()) {
                throw new ChaincodeException("Document not found for ID: " + documentID , DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        // Convert the JSON string to a JSONObject
        Document doc = genson.deserialize(documentJSON,Document.class);
        doc.setSignable(signable);
        String sortedJson = genson.serialize(doc);

        stub.putStringState(documentID, sortedJson);
        return doc;
    }

        /**
     * Deletes document on the ledger.
     *
     * @param ctx the transaction context
     * @param assetID the ID of the asset being deleted
     */
    @Transaction(intent = Transaction.TYPE.SUBMIT)
    public void DeleteDocument(final Context ctx, final String documentID) {
        ChaincodeStub stub = ctx.getStub();

        if (!CheckDocumentExists(ctx, documentID)) {
            String errorMessage = String.format("Document %s does not exist", documentID);
            System.out.println(errorMessage);
            throw new ChaincodeException(errorMessage, DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        stub.delState(documentID);
    }

        /**
     * Retrieves all assets from the ledger.
     *
     * @param ctx the transaction context
     * @return array of assets found on the ledger
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public String GetAllDocuments(final Context ctx) {
        ChaincodeStub stub = ctx.getStub();

        List<Document> queryResults = new ArrayList<>();

        // To retrieve all assets from the ledger use getStateByRange with empty startKey & endKey.
        // Giving empty startKey & endKey is interpreted as all the keys from beginning to end.
        // As another example, if you use startKey = 'asset0', endKey = 'asset9' ,
        // then getStateByRange will retrieve asset with keys between asset0 (inclusive) and asset9 (exclusive) in lexical order.
        QueryResultsIterator<KeyValue> results = stub.getStateByRange("", "");

        for (KeyValue result: results) {
            Document document = genson.deserialize(result.getStringValue(), Document.class);
            System.out.println(document);
            queryResults.add(document);
        }

        final String response = genson.serialize(queryResults);

        return response;
    }

    

    /**
     * Retrieves all documents within a specified range from the ledger.
     *
     * @param ctx the transaction context
     * @param startKey the start key for the range (inclusive)
     * @param endKey the end key for the range (exclusive)
     * @return JSON array of documents found within the range
     */
    @Transaction(intent = Transaction.TYPE.EVALUATE)
    public String GetAllDocumentsInRange(final Context ctx, final String startKey, final String endKey) {
        ChaincodeStub stub = ctx.getStub();

        if (startKey.equals(endKey)) {
            String errorMessage = String.format("Entered two of the same key");
            System.out.println(errorMessage);
            throw new ChaincodeException(errorMessage, DocumentTransferErrors.DOCUMENT_NOT_FOUND.toString());
        }

        List<Document> queryResults = new ArrayList<>();

        // Use getStateByRange with startKey and endKey
        // This will retrieve all documents with keys between startKey (inclusive) and endKey (exclusive)
        QueryResultsIterator<KeyValue> results = stub.getStateByRange(startKey, endKey);

        // Iterate through the results and deserialize each document
        for (KeyValue result : results) {
            Document document = genson.deserialize(result.getStringValue(), Document.class);
            queryResults.add(document);
        }

        // Serialize the list of documents to JSON and return
        return genson.serialize(queryResults);
    }

    


}